Week8/AutoShop23/Models/Technician.cs
using System.ComponentModel.DataAnnotations;

namespace AutoShop23.Models
{
    public class Technician
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        [Display(Name = "Tech First Name")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(30)]
        [Display(Name = "Tech Last Name")]
        public string LastName { get; set; }
        [Required]
        //This means that this will always be exactly 9 characters
        [StringLength(9, MinimumLength = 9)]
        public string EmployeeNumber { get; set; }
        //foreign key to technicianstatus Id
        public int TechnicianStatusId { get; set; }

        //navigation properties
        //each technician has multiple serviceperformed
        public IEnumerable<ServicePerformed> ServicesPerformed { get; set; }
        public TechnicianStatus TechnicianStatus { get; set; }

    }
}

Week8/AutoShop23/Controllers/TechnicianController.cs
using AutoShop23.Data;
using AutoShop23.Models;
using AutoShop23.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AutoShop23.Controllers
{
    public class TechnicianController : Controller
    {
        //fields
        ApplicationDbContext _context;

        public TechnicianController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //Json() does not work when using the Include() method
            //We want to load all of the technicians and Include the
            //navigation property to technician status
            //what this is going to do. It is going to pull the record
            //from technicianstatus and place it in the navigation property
            //You only have access to Include when dealing with a collection
            IEnumerable<Technician> technicians = _context.Technicians.Include(x => x.TechnicianStatus);
            return View(technicians);
        }
        //To create a Technician we have to have a techstatus
        //Either you send them to another page where they select a status and then take
        //the selected status as a parameter in Create()
        //OR
        //We include a selectlist with all of the possible statuses in the Create View()
        //Lets create a selectList with the statuses
        public IActionResult Create()
        {
            //You can use the viewbag to do this
            //I prefer to make a ViewModel (DTO - Data Transfer Object)
            //We need to create the selectlist
            IEnumerable<SelectListItem> techStatusList = _context.TechnicianStatuses.Select(x => new SelectListItem
            {
                Text = x.Status,
                Value = x.Id.ToString()
            });
            TechCreateVM techCreateVM = new TechCreateVM
            {
                TechStatusList = techStatusList
            };
            return View(techCreateVM);
        }
        [HttpPost]
        public IActionResult Create(TechCreateVM techCreateVM)
        {
            if(!ModelState.IsValid)
            {
                //repopulate the list
                techCreateVM.TechStatusList = _context.TechnicianStatuses.Select(x => new SelectListItem
                {
                    Text = x.Status,
                    Value = x.Id.ToString()
                });
                return View(techCreateVM);
            }
            //We need to create a new Technician from the techCreateVM
            Technician technician = new Technician
            {
                FirstName = techCreateVM.FirstName,
                LastName = techCreateVM.LastName,
                EmployeeNumber = techCreateVM.EmployeeNumber,
                TechnicianStatusId = techCreateVM.TechnicianStatusId
            };
            _context.Technicians.Add(technician);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        //Details endpoint
        public IActionResult Details(int  id)
        {
            if(id == 0)
            {
                return NotFound();
            }
            Technician technician = _context.Technicians.SingleOrDefault(x => x.Id == id);
            if(technician == null)
            {
                return NotFound();
            }
            //Pulling the technicianstatus for our techncian and passing it to view
            //using the navigation property
            //If you have one instance of an entity and need to populate a naviation property
            //you do it by hand
            technician.TechnicianStatus = _context.TechnicianStatuses.
                SingleOrDefault(x => x.Id == technician.TechnicianStatusId);
            return View(technician);
        }
    }
}

Week8/AutoShop23/Views/Technician/Create.cshtml
@model TechCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Technician</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeNumber" class="control-label"></label>
                <input asp-for="EmployeeNumber" class="form-control" />
                <span asp-validation-for="EmployeeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TechnicianStatusId" class="control-label"></label>
                <select asp-for="TechnicianStatusId" class ="form-control" asp-items="@Model.TechStatusList"></select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary p-2 mt-2">Create <i class="fa-solid fa-square-plus"></i></button>
                <a asp-controller="Technician" asp-action="Index" class="btn btn-outline-warning p-2 mt-2">
                    Back to list <i class="fa-solid fa-square-caret-left"></i>
                </a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Week8/AutoShop23/Views/Technician/Details.cshtml
@model Technician

<h1>Details</h1>

<div>
    <h4>Technician</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Model.FirstName
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Model.LastName
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Model.EmployeeNumber
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TechnicianStatus)
        </dt>
        <dd class = "col-sm-10">
            @Model.TechnicianStatus.Status
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Week8/AutoShop23/Views/Technician/Index.cshtml
@model IEnumerable<Technician>

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechnicianStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (Technician technician in Model) {
        <tr>
            <td>
                @technician.FirstName
            </td>
            <td>
                @technician.LastName
            </td>
            <td>
                @technician.EmployeeNumber
            </td>
            <td>
                @technician.TechnicianStatus.Status
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@technician.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@technician.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@technician.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>